import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

const SimpleText = dynamic(() => import("host/SimpleText"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Consumer App !</h1>

      <SimpleText text="some test" />
    </div>
  )
}

