import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

const SimpleText = dynamic(() => import("host/SimpleText"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Consumer App !</h1>

      <SimpleText text="Yikes passing from consumer app!" >
        <quote>
          Without a doubt one of the most important poems of the 20th century. “It has never lost its glamour,” Paul Muldoon observed. “It has never failed to be equal to both the fracture of its own era and what, alas, turned out to be the even greater fracture of the ongoing 20th century and now, it seems, the 21st century.” See also: “The Love Song of J. Alfred Prufrock.
        </quote>
        <p>
         -- T. S. Eliot, “The Waste Land”
        </p>
      </SimpleText> 
    </div>
  )
}

